Algoritmo "circulo"

Var

   r1, r2, area1, area2 : real


Inicio


   escreval ("Exemplo 1:")
   escreval ("Digite o valor do raio do circulo: ")
   leia (r1)
   
   area1 <- Pi * Exp (r1, 2)
   
   escreval ("AREA = ", area1:8:3)
   escreval
   escreval ("Exemplo 2:")
   escreval ("Digite o valor do raio do circulo: ")
   leia (r2)
   
   area2 <- Pi * Exp (r2, 2)
   
   escreval ("AREA = ", area2:8:3)


Fimalgoritmo