Algoritmo "soma"

Var

   x1, x2, y1, y2, soma1, soma2 : inteiro


Inicio

    escreval ("Digite o valor de X: ")
    leia (x1)
    escreval ("Digite o valor de Y: ")
    leia (y1)
    
    soma1 <- x1 + y1
    escreval
    escreval ("SOMA = ", soma1)
    escreval
    escreval ("Digite o valor de X: ")
    leia  (x2)
    escreval ("Digite o valor de Y: ")
    leia (y2)
    
    soma2 <- x2 + y2
    escreval
    escreval ("SOMA = ", soma2)
  
  
  


Fimalgoritmo